// Nomes das abas, exatamente como em PLANILHA_CONSOLIDADA_K4.xlsx — mude
// aqui se renomear alguma aba na planilha real.
const SHEETS = {
  CLIENTES: 'CLIENTES',
  PROCESSOS_MARCA: 'PROCESSOS_MARCA',
  OPOSICOES: 'OPOSICOES',
  INDEFERIMENTOS: 'INDEFERIMENTOS',
  EXIGENCIAS: 'EXIGENCIAS',
  NULIDADES: 'NULIDADES',
  ARQUIVADOS: 'ARQUIVADOS',
  EXAME_PRIORITARIO: 'EXAME_PRIORITARIO',
  NAMING: 'NAMING',
  FALE_CONOSCO: 'FALE_CONOSCO',
  PROCESSOS_PATENTE: 'PROCESSOS_PATENTE',
  PROCESSOS_DESENHO_INDUSTRIAL: 'PROCESSOS_DESENHO_INDUSTRIAL',
  ACOMP_MENSAL: 'ACOMP_MENSAL',
  DESPACHOS_MARCAS: 'DESPACHOS_MARCAS',
  DESPACHOS_PATENTES: 'DESPACHOS_PATENTES',
  DESPACHOS_DESENHO_INDUSTRIAL: 'DESPACHOS_DESENHO_INDUSTRIAL',
  DESPACHOS_PENDENTES_CONFIRMACAO: 'DESPACHOS_PENDENTES_CONFIRMACAO',
  PAINEL_PRAZOS: 'PAINEL_PRAZOS',
  CONFIG_RPI: 'CONFIG_RPI',
  CONFIG_DESPACHO_MARCA: 'CONFIG_DESPACHO_MARCA',
  CONFIG_DESPACHO_PATENTE: 'CONFIG_DESPACHO_PATENTE',
  CONFIG_ESTRATEGIA_INDEFERIMENTO: 'CONFIG_ESTRATEGIA_INDEFERIMENTO',
  CONFIG_TIPO_EXIGENCIA: 'CONFIG_TIPO_EXIGENCIA',
};

const SECAO_LABEL = {
  marcas: 'Marcas',
  patentes: 'Patentes',
  desenho: 'Desenho Industrial',
};

const SHEET_PROCESSOS_POR_SECAO = {
  marcas: SHEETS.PROCESSOS_MARCA,
  patentes: SHEETS.PROCESSOS_PATENTE,
  desenho: SHEETS.PROCESSOS_DESENHO_INDUSTRIAL,
};
